version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
    environment:
      - TZ=America/Lima
      - PLEX_GID=1000
      - PLEX_UID=1001
    volumes:
      - ./plex/config:/config        # Para la configuración de Plex
      - ./plex/transcode:/transcode  # Para los archivos temporales de transcodificación
      - ./plex/media:/data           # Aquí irán tus archivos multimedia (películas, música, etc.)
